### ISSUE TITLE
Are fonts possible?

### ISSUE THREAD

**Issue by wumfi** [phoreglad/pico-epaper#1]
You have saved my life with this repo.  Whilst I'm an experienced Linux guy, I have little to no Micropython experience, so this enabled me to finally get my 3.7 ePaper working!  Thank you.

Once question if I may?  Is it possible to implement fonts within the text() method?  I've seen lots of examples online, but I am really struggling to get them to work.  Is there a simple(ish) method?

**Comment by phoreglad** [comment]
I'm glad you find it useful.

Unfortunately, it's not possible to use different fonts with the `text()` method because it's not supported by the underlying `FrameBuffer` class.

It can, however, be done using [micropython-font-to-py and Writer class](https://github.com/peterhinch/micropython-font-to-py) by Peter Hinch. This approach requires creating a dummy device class that inherits from `FrameBuffer` since my driver doesn't do that, but other than that it's really easy to use. I'll add an example in near future, so stay tuned.

**Comment by wumfi** [comment]
Thank you for replying. I'll wait with baited breath!

**Comment by phoreglad** [comment]
And done, see the examples folder for details.

**Comment by wumfi** [comment]
You sir, are a gentleman and a scholar.  Thank you!

**Comment by wumfi** [comment]
It works!  But I found a bug, I think anyway.  If I run your code as is, then the paper goes completely black.

If I add `epd.fill()` before `epd.blit(dummy, 0, 0, key=1)`, then it clears the screen first and then shows the lorem ipsum.

Thank you!

**Comment by wumfi** [comment]
Also, there is a very long pause between:

`Orientation: Horizontal. Reversal: False. Width: 480. Height: 280.
Start row = 0 col = 0`

and 

`Data loading time: 2009 ms`

This could very well be me doing something wrong of course?

**Comment by wumfi** [comment]
Sorry to spam.  I just added a time before and after.  This could just be how long it takes the Pico to render the font I suppose.  Not sure if it's possible to save the rendered info, so that it can just include that?  As I say, I'm very much a beginner with this!

`Time now: 19:58:15`
`Orientation: Horizontal. Reversal: False. Width: 480. Height: 280.`
`Start row = 0 col = 0`
`Data loading time: 1999 ms`
`Time now: 19:58:40`

**Comment by phoreglad** [comment]
> It works! But I found a bug, I think anyway. If I run your code as is, then the paper goes completely black.
> 
> If I add `epd.fill()` before `epd.blit(dummy, 0, 0, key=1)`, then it clears the screen first and then shows the lorem ipsum.
> 
> Thank you!

Yep, that's a bug. All buffers should be cleared on initialisation but aren't. It seems I have corrected it in the file I have on my Pico but forgot to include it in the repo. Thanks for catching it!



> This could just be how long it takes the Pico to render the font I suppose.

Yes, you're right. Pico just needs some time to render all this text with word wrapping. It should be much faster with shorter texts where wrapping is not needed.

> Not sure if it's possible to save the rendered info so that it can just include that?

The buffer containing rendered text is just a bytearray, so it should be possible to save it to a file and use it later to blit onto the screen. You might want to use the smallest possible buffer that can fit the text you need to avoid using too much memory.
