### ISSUE TITLE
Setting own pins

### ISSUE THREAD

**Issue by wumfi** [phoreglad/pico-epaper#4]
Just pulled your latest code, and found a problem:

I have my ESP32-S2 connected to the screen, rather than a Pico.  Therefore, in the past I had just hard coded the pins into the init method.  Now with the new code base, I use the following instead:

`epd = Eink(rotation=270, cs_pin=36, dc_pin=14, reset_pin=8, busy_pin=9)`

It then throws an error stating:

`AttributeError: 'int' object has no attribute 'init'`

I managed to get it working by changing each piece of code relating to the pin assignment.  This may not be the best solution, but for each pin I changed the else part.  Example:

From:
```
if reset_pin is None:
    self._rst = Pin(12, Pin.OUT, value=0)
else:
    self._rst = reset_pin
    self._rst.init(Pin.OUT, value=0)
```

To:
```
if reset_pin is None:
    self._rst = Pin(12, Pin.OUT, value=0)
else:
    self._rst = Pin(reset_pin, Pin.OUT, value=0)
```

I don't know if there are any ramifications from making such a change, but I've tested out the text and graphics methods, and it does appear to work ok.

**Comment by phoreglad** [comment]
You need to pass Pin object to the constructor, not the pin number. In your case initialisation should look like:
```python
epd = Eink(rotation=270, cs_pin=Pin(36), dc_pin=Pin(14), reset_pin=Pin(8), busy_pin=Pin(9))
```
