### ISSUE TITLE
Showtime!

### ISSUE THREAD

**Issue by bitblitz4use** [phoreglad/pico-epaper#9]
Hi all,
can't get the examples running. 
Hardware used: 

- Waveshare Pico-ePaper 2.9B Version 3.
- Pico W

Funny thing is i dont get errors its just saying:
Hell output:
`>>> %Run -c $EDITOR_CONTENT
show took: 217 ms to finish
show used around 240 B of memory
show took: 217 ms to finish
show used around 240 B of memory
>>>`

But no display output. SPI wiring seems to be ok running code from the original Waveshare lib. 

Any idea what I am missing? 
I run Pico_ePaper.py in Thonny with MicroPhyton installed as interpreter.

THX!

**Comment by phoreglad** [comment]
This driver is meant for 3.7" display and will not work with 2.9" one.
